// {"editable": []}
/*
 * thereIsNoLevel.js
 * 
 * You're still here? Maybe the whole 'win the game 
 * and get back to the real world' didn't work...
 * 
 * You can play the maze as many times as you like if
 * you're still killing time. Press either of the
 * Execute or Reset buttons to generate a new maze.
 * 
 * I would also appreciate it if you could take this
 * survey: https://www.surveymonkey.co.uk/r/929B8YY
 * 
 * Thank you!
 */
function startLevel(map) {
    map.placePlayer(7, 5);
    map.player.draw();

    var autoGeneratedMaze = new ROT.Map.DividedMaze(map.getWidth(), map.getHeight());

    autoGeneratedMaze.create( function (x, y, mapValue) {

        // don't write maze over player
        if (map.player.atLocation(x,y)) {
            return 0;
        }

        else if (mapValue === 1) {
            map.placeObject(x,y, 'wall');
        }
        else {
            map.placeObject(x,y,'empty');
        }
    });

    map.placeObject(map.getWidth()-5, map.getHeight()-4, 'goal');
    display.drawAll(map);

    msg.drawText(0, 0, "You've completed all of the available levels, hopefully you've enjoyed the game. Thanks for playing!");
}