// {"editable": [[17, 17], [34, 34]]}
/*
 * Level 1
 * 
 * Thanks for volunteering, though I'm not sure why you'd want to
 * be 'zapped into Cyber Space' with no guarantee of getting back out.
 * They didn't tell you that part? Oh...
 *
 * Anyway, here's the first level. It's just a randomly generated 
 * maze. You could probably win this one without doing anything 
 * in the editor, but where's the fun in that?
 * 
 * What, you want a hint? No comment.
 */
function startLevel(map) {
    map.placePlayer(7, 5);
    map.player.draw();

    var autoGeneratedMaze = new ROT.Map.DividedMaze(map.getWidth(), map.getHeight());

    autoGeneratedMaze.create( function (x, y, mapValue) {

        // don't write maze over player
        if (map.player.atLocation(x,y)) {
            return 0;
        }

        else if (mapValue === 1) {
            map.placeObject(x,y, 'wall');
        }
        else {
            map.placeObject(x,y,'empty');
        }
    });
    
    map.placeObject(map.getWidth()-5, map.getHeight()-4, 'goal');
}